### ISSUE TITLE
Seems SPI is not working with the latest Arduino_Core_STM32

### ISSUE THREAD

**Issue by buptlgq** [r-pv/rSTM32F030C8T6_ProMiniPlus#1]
Try the latest Arduino_Core_STM32 and SPI is not working?
How to use the "stm32f0xx_hal_conf.h" in your respo?

**Comment by r-pv** [comment]
Hi, I tested the SPI with a display (ST7735) and a microSD card and all works under the new 1.7 core, I'm using the previous arduino ide, if you're using the latest version may be the problem (I saw a issue on the arduino_core_stm32 github where it says "on hold" for the new IDE).

**Comment by r-pv** [comment]
Regarding to the HAL config, I include a HAL with all hardware (I2C, SPI, ADC, etc.) enabled by default, for some reason this file was required for the core were my variants for other boards (f103ve and f405rg) didn't. So, if you're running out of flash and want to disable hardware that you don't  be using just create a file named "hal_conf_extra.h" on your sketch folder and with the lines that you want to disable, example:
```
#define HAL_ADC_MODULE_DISABLED
#define HAL_I2C_MODULE_DISABLED
#define HAL_RTC_MODULE_DISABLED
#define HAL_SPI_MODULE_DISABLED
#define HAL_TIM_MODULE_DISABLED
#define HAL_DAC_MODULE_DISABLED
#define HAL_EXTI_MODULE_DISABLED
#define HAL_ETH_MODULE_DISABLED
#define HAL_SD_MODULE_DISABLED
#define HAL_QSPI_MODULE_DISABLED
```

for other HAL options please check: https://github.com/stm32duino/wiki/wiki/HAL-configuration#core-version--150-1

**Comment by r-pv** [comment]
So I got not reply from you, I'll assume that was a "_connection error_" (it happens to me a lot :P ), so I'm closing this issue, but if you still got problems just open a new issue and I'll be back at it. Cheers.
